from __future__ import annotations

import re

STOPWORDS = {
    "que",
    "qui",
    "quin",
    "quina",
    "quins",
    "quines",
    "com",
    "quan",
    "on",
    "per",
    "amb",
    "des",
    "para",
    "por",
    "sobre",
    "entre",
    "desde",
    "hasta",
    "sin",
    "segun",
    "según",
    "del",
    "de",
    "la",
    "el",
    "les",
    "els",
    "los",
    "las",
    "una",
    "uno",
    "unos",
    "unas",
    "nou",
    "nova",
    "nous",
    "noves",
    "data",
    "generalitat",
    "consell",
    "conselleria",
    "presidencia",
    "presidència",
    "departament",
    "govern",
    "ha",
    "han",
    "s'ha",
    "es",
    "se",
    "si",
    "sí",
    "ja",
    "ya",
    "esta",
    "este",
    "aquesta",
    "aquest",
    "hoy",
    "ahir",
    "ayer",
    "donde",
    "dónde",
    "cual",
    "cuál",
    "cuales",
    "cuáles",
    "como",
    "cómo",
    "quiero",
    "ver",
    "buscar",
    "encontrar",
    "consultar",
    "participar",
    "poder",
    "puedo",
    "podria",
    "podría",
    "algun",
    "algún",
    "alguna",
    "algunos",
    "algunas",
    "cualquier",
    "cualquiera",
    "cualesquiera",
    "sera",
    "serà",
}

SHORT_TOKEN_ALLOWLIST = {
    "ope",
    "umh",
    "ivass",
    "gva",
    "c1",
    "c2",
    "a1",
    "a2",
    "b1",
    "b2",
}

GENERIC_TERMS = {
    "anuncio",
    "resolucion",
    "resolución",
    "decreto",
    "orden",
    "acuerdo",
    "convocatoria",
    "convocar",
    "bases",
    "base",
    "lista",
    "listado",
    "listes",
    "admitidos",
    "admitidas",
    "excluidos",
    "excluidas",
    "tribunal",
    "tribunales",
    "concurso",
    "oposicion",
    "oposición",
    "publicado",
    "publicada",
    "publicacion",
    "publicación",
    "modificacion",
    "modificación",
    "correccion",
    "corrección",
    "nombramiento",
    "cese",
    "plaza",
    "plazas",
    "puesto",
    "puestos",
    "oferta",
    "empleo",
    "publico",
    "público",
    "provision",
    "provisión",
    "resolucio",
    "resolució",
    "ayuntamiento",
    "universidad",
    "universitat",
    "consorcio",
    "generalitat",
    "personal",
    "convocado",
    "convocada",
    "convocó",
    "salido",
    "publicaron",
    "aprobó",
    "aprobado",
}

LOW_SIGNAL_TERMS = {
    "publicado",
    "publicada",
    "publicacion",
    "publicación",
    "publicar",
    "salido",
    "salida",
    "salir",
    "aprobado",
    "aprobada",
    "aprobó",
    "aprobacion",
    "aprobación",
    "aprobar",
    "convocado",
    "convocada",
    "convocar",
    "modificado",
    "modificada",
    "modificar",
}

CONNECTORS = {
    "de",
    "del",
    "d'",
    "l'",
    "la",
    "el",
    "i",
    "y",
    "da",
    "do",
    "dos",
    "des",
    "en",
    "para",
    "per",
    "a",
    "al",
}

VALENCIAN_MARKERS = {
    "s'ha",
    "ha estat",
    "per a",
    "llocs",
    "lloc",
    "nomenament",
    "cessament",
    "errades",
    "correccio",
    "correcció",
    "publicat",
    "convocat",
    "convocada",
    "resolucio",
    "resolució",
    "decret",
    "generalitat",
    "consell",
    "conselleria",
}


def tokenize(text: str) -> list[str]:
    return re.findall(r"[\w·'/-]+", text.lower())


def keep_token(token: str) -> bool:
    if len(token) >= 4:
        return True
    if token in SHORT_TOKEN_ALLOWLIST:
        return True
    if any(ch.isdigit() for ch in token) and len(token) >= 2:
        return True
    if re.fullmatch(r"[a-z]\d", token):
        return True
    return False


def has_content_tokens(text: str) -> bool:
    tokens = [t for t in tokenize(text) if keep_token(t) and t not in STOPWORDS]
    return len(tokens) >= 2
